name: Create Tag
on:
  push:
    branches:
      - main
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: |
        chmod +x ./scripts/gitTag.sh
        ./scripts/gitTag.sh
      shell: bash
