name: Create Tag
on:
  push:
    branches:
      - main
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: |
        chmod +x .github/workflows/scripts/gitTag.sh
        .github/workflows/scripts/gitTag.sh -v patch
      shell: bash
